### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by lordcrekit** [lordcrekit/MI-449-SS17-740-html-terminal-and-git-_u9ftI#1]
@egillespie Can you take a look at this? It's [hosted here](https://lordcrekit.github.io/MI-449-SS17-740-html-terminal-and-git-_u9ftI/) and meets the following criteria:

- [x] A knock-knock joke is displayed when visiting the website
- [x] The code is pushed to GitHub
- [x] The website is hosted on GitHub Pages

**Comment by egillespie** [comment]
Looks good. We weren't expecting any HTML in this lesson, but it looks like you already have some familiarity. If you find the first handful of lessons easy, don't worry. They'll get more challenging. If you're ever waiting on new lessons to appear, let us know!

:shipit:
